<?php
/**
 */

namespace execut\pages;


use yii\i18n\PhpMessageSource;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->initI18n();
    }

    public function initI18n() {
        \yii::$app->i18n->translations['execut/pages'] = [
            'class' => PhpMessageSource::class,
            'basePath' => 'vendor/execut/pages/messages',
        ];
    }
}