<?php
/**
 */

namespace execut\pages\controllers;


use execut\actions\Action;
use execut\pages\action\adapter\ShowPage;
use execut\navigation\Behavior;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ErrorAction;

class FrontendController extends Controller
{
    public function behaviors()
    {
        if (YII_ENV === 'dev') {
            return [];
        }

        if (!$this->module->isCacheEnabled) {
            return [];
        }

        $time = $this->module->getLastModificationTime();

        return [
            'httpCache' => [
                'class' => 'yii\filters\HttpCache',
                'only' => ['index'],
                'lastModified' => function () use ($time) {
                    return $time;
                },
                'etagSeed' => function () use ($time) {
                    return $time;
                },
            ],
            'pageCache' => [
                'class' => 'yii\filters\PageCache',
                'only' => ['index'],
                'duration' => 0,
                'dependency' => [
                    'class' => 'yii\caching\TagDependency',
                    'tags' => [
                        'pages',
                        $time,
                    ],
                ],
                'variations' => [
                    \Yii::$app->request->url . $time,
                ]
            ],
        ];
    }

    public function actions()
    {
        if (\yii::$app->request->url === '/') {
            $view = $this->module->indexViewPath;
        } else {
            $view = 'index';
        }

        return ArrayHelper::merge(parent::actions(), [
            'index' => [
                'class' => Action::class,
                'adapter' => [
                    'class' => ShowPage::class,
                ],
                'view' => $view,
            ],
            'error' => [
                'class' => ErrorAction::class,
            ],
        ]); // TODO: Change the autogenerated stub
    }
}